from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Calculate top-k ranking metrics from evaluation CSV.")
    parser.add_argument(
        "--csv",
        default="data/processed/final_test_evaluation.csv",
        help="Evaluation CSV generated by scripts/evaluate_matching.py.",
    )
    parser.add_argument(
        "--score-columns",
        nargs="+",
        default=["semantic_score", "overall_score"],
        help="Score columns used for ranking.",
    )
    parser.add_argument(
        "--k",
        nargs="+",
        type=int,
        default=[50, 100, 200],
        help="Top-k cutoffs.",
    )
    return parser.parse_args()


def load_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as file:
        return list(csv.DictReader(file))


def precision_at_k(rows: list[dict[str, str]], score_column: str, k: int, positive_labels: set[str]) -> float:
    ranked_rows = sorted(rows, key=lambda row: float(row[score_column]), reverse=True)
    top_rows = ranked_rows[:k]
    if not top_rows:
        return 0.0
    positive_count = sum(row["label"] in positive_labels for row in top_rows)
    return positive_count / len(top_rows)


def main() -> None:
    args = parse_args()
    rows = load_rows(Path(args.csv))
    if not rows:
        raise ValueError(f"No rows found in {args.csv}")

    print(f"Evaluation CSV: {args.csv}")
    print(f"Rows: {len(rows)}")
    print()

    for score_column in args.score_columns:
        print(f"Ranking by {score_column}")
        for k in args.k:
            good_precision = precision_at_k(rows, score_column, k, {"Good Fit"})
            acceptable_precision = precision_at_k(rows, score_column, k, {"Good Fit", "Potential Fit"})
            print(f"  Precision@{k} Good Fit: {good_precision:.4f}")
            print(f"  Precision@{k} Potential-or-Good Fit: {acceptable_precision:.4f}")
        print()


if __name__ == "__main__":
    main()
